CREATE DATABASE Bcadm_login;
USE Bcadm_login;

CREATE TABLE USUARIO (
ID_USU INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
EMAIL VARCHAR(30),
SENHA VARCHAR(8)
);

CREATE TABLE DESPESAS (
COD_DESP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_DESP VARCHAR(10),
VALOR_DESP NUMERIC(9,2),
DESCRICAO VARCHAR(60),
DATA_VENCIMENTO DATE
);

CREATE TABLE TIPO_DESPESA (
COD_TPD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR(30)
);

CREATE TABLE DESP_TIPO (
COD_DESP INTEGER,
COD_TPD INTEGER,
PRIMARY KEY (COD_DESP, COD_TPD),
FOREIGN KEY (COD_DESP) REFERENCES DESPESAS (COD_DESP),
FOREIGN KEY (COD_TPD) REFERENCES TIPO_DESPESA (COD_TPD)
);

CREATE TABLE RECEITA (
COD_RCT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_RCT VARCHAR(10),
VALOR_RCT NUMERIC(9,2),
DESCRICAO VARCHAR(60),
DATA_RECEBIMENTO DATE
);

CREATE TABLE TIPO_RECEITA (
COD_TPR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CATEGORIA VARCHAR(30)
);

CREATE TABLE RCT_TIPO (
COD_RCT INTEGER,
COD_TPR INTEGER,
PRIMARY KEY (COD_RCT, COD_TPR),
FOREIGN KEY (COD_RCT) REFERENCES RECEITA (COD_RCT),
FOREIGN KEY (COD_TPR) REFERENCES TIPO_RECEITA (COD_TPR)
);

CREATE TABLE INVESTIMENTOS (
COD_INV INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_INV VARCHAR(30),
VALOR_INV NUMERIC(9,2)
);

INSERT INTO INVESTIMENTOS (
INVESTIMENTOS.COD_INV,
INVESTIMENTOS.NOME_INV,
INVESTIMENTOS.VALOR_INV
)

VALUES (
1,
"CASA PRÓPRIA",
200.000
);

SELECT*FROM METAS;

RENAME TABLE INVESTIMENTOS TO METAS;

ALTER TABLE METAS CHANGE COD_INV COD_MT INT;
ALTER TABLE METAS
  CHANGE COD_MT COD_MT int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE METAS CHANGE NOME_INV NOME_MT VARCHAR(30);
ALTER TABLE METAS CHANGE VALOR_INV VALOR_MT NUMERIC(9,2);
